In [56]:
import numpy as np
import pandas as pd

# Assign input, output, weight, learning rate

In [57]:
data = {'input1':[0,0,1,1],'input2':[0,1,0,1], 'output':[0,1,1,1]}
df = pd.DataFrame(data)
df

input1  input2  output
0       0       0       0
1       0       1       1
2       1       0       1
3       1       1       1

In [58]:
#input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
input_features = df[['input1','input2']].to_numpy()
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [59]:
#target_output = np.array([[0,1,1,1]])
target_output = df[['output']].to_numpy()
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [66]:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [67]:
bias = 0.3
lr = 0.05

# Define Functions

In [26]:
# Define sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Define derivative of sigmoid function
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [77]:
for epoch in range(10000):
    inputs = input_features
    in_o = np.dot(inputs, weights) + bias
    out_o = sigmoid(in_o)
    error = out_o - target_output
    
    x = error.sum()
    if epoch%1000 == 0:
        print('Epoch:',epoch,'Error Sum:',x)
    
    dError_dOut = error
    dOut_dIn = sigmoid_der(out_o)
    
    deriv = dError_dOut * dOut_dIn
    
    inputs = input_features.T
    deriv_final = np.dot(inputs, deriv)
    
    weights -= lr * deriv_final
    #print('Weight:',weights)
    
    for i in deriv:
        bias -= lr * i
        #print('Bias:',bias)

Epoch: 0 Error Sum: -0.00020252167143973432
Epoch: 1000 Error Sum: -0.00021491565649722072
Epoch: 2000 Error Sum: -0.00022175398447425373
Epoch: 3000 Error Sum: -0.00022485655501638252
Epoch: 4000 Error Sum: -0.0002254232653113343
Epoch: 5000 Error Sum: -0.00022426146076638676
Epoch: 6000 Error Sum: -0.00022192361452227569
Epoch: 7000 Error Sum: -0.00021879308150700438
Epoch: 8000 Error Sum: -0.00021513886180585945
Epoch: 9000 Error Sum: -0.00021115135072666963


In [78]:
print('Weights:',weights)
print('Bias:',bias)

Weights: [[8.63277703]
 [8.6328387 ]]
Bias: [-3.97070356]


In [70]:
# Prediction with the new model for [1,1], groud truth result = 1

In [79]:
single_point = np.array([1,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
result2

array([0.99064155])

In [72]:
# Prediction with the new model for [0,0], groud truth result = 0

In [80]:
single_point = np.array([0,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
result2

array([0.01851104])