In [41]:
import numpy as np
import pandas as pd

# Assign input, output, weight, learning rate

In [44]:
data = {'input1':[0,0,1,1],'input2':[0,1,0,1], 'output':[0,1,1,1]}
df = pd.DataFrame(data)
df

input1  input2  output
0       0       0       0
1       0       1       1
2       1       0       1
3       1       1       1

In [49]:
#input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
input_features = df[['input1','input2']].to_numpy()
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [50]:
#target_output = np.array([[0,1,1,1]])
target_output = df[['output']].to_numpy()
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [51]:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [52]:
bias = 0.3
lr = 0.05

# Define Functions

In [26]:
# Define sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Define derivative of sigmoid function
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [54]:
for epoch in range(1000):
    inputs = input_features
    in_o = np.dot(inputs, weights) + bias
    out_o = sigmoid(in_o)
    error = out_o - target_output
    
    x = error.sum()
    print('Epoch:',epoch,'Error Sum:',x)
    
    dError_dOut = error
    dOut_dIn = sigmoid_der(out_o)
    
    deriv = dError_dOut * dOut_dIn
    
    inputs = input_features.T
    deriv_final = np.dot(inputs, deriv)
    
    weights -= lr * deriv_final
    #print('Weight:',weights)
    
    for i in deriv:
        bias -= lr * i
        #print('Bias:',bias)

Epoch: 0 Error Sum: -6.430413898600527e-05
Epoch: 1 Error Sum: -6.430354492650316e-05
Epoch: 2 Error Sum: -6.430295087719688e-05
Epoch: 3 Error Sum: -6.43023568391108e-05
Epoch: 4 Error Sum: -6.430176281204628e-05
Epoch: 5 Error Sum: -6.430116879524439e-05
Epoch: 6 Error Sum: -6.430057478962539e-05
Epoch: 7 Error Sum: -6.429998079543215e-05
Epoch: 8 Error Sum: -6.429938681157786e-05
Epoch: 9 Error Sum: -6.429879283875554e-05
Epoch: 10 Error Sum: -6.429819887632336e-05
Epoch: 11 Error Sum: -6.429760492530651e-05
Epoch: 12 Error Sum: -6.429701098483766e-05
Epoch: 13 Error Sum: -6.429641705550139e-05
Epoch: 14 Error Sum: -6.429582313687444e-05
Epoch: 15 Error Sum: -6.42952292291988e-05
Epoch: 16 Error Sum: -6.429463533228624e-05
Epoch: 17 Error Sum: -6.429404144615673e-05
Epoch: 18 Error Sum: -6.429344757117022e-05
Epoch: 19 Error Sum: -6.429285370690343e-05
Epoch: 20 Error Sum: -6.429225985350034e-05
Epoch: 21 Error Sum: -6.429166601075974e-05
Epoch: 22 Error Sum: -6.429107217914565e-05


Epoch: 415 Error Sum: -6.405853429042319e-05
Epoch: 416 Error Sum: -6.405794471551086e-05
Epoch: 417 Error Sum: -6.405735515158714e-05
Epoch: 418 Error Sum: -6.40567655981238e-05
Epoch: 419 Error Sum: -6.405617605558748e-05
Epoch: 420 Error Sum: -6.40555865236694e-05
Epoch: 421 Error Sum: -6.405499700272519e-05
Epoch: 422 Error Sum: -6.405440749222661e-05
Epoch: 423 Error Sum: -6.405381799275134e-05
Epoch: 424 Error Sum: -6.405322850377287e-05
Epoch: 425 Error Sum: -6.405263902574832e-05
Epoch: 426 Error Sum: -6.405204955848946e-05
Epoch: 427 Error Sum: -6.405146010168752e-05
Epoch: 428 Error Sum: -6.405087065580652e-05
Epoch: 429 Error Sum: -6.405028122076321e-05
Epoch: 430 Error Sum: -6.404969179624274e-05
Epoch: 431 Error Sum: -6.404910238294332e-05
Epoch: 432 Error Sum: -6.4048512979995e-05
Epoch: 433 Error Sum: -6.404792358775772e-05
Epoch: 434 Error Sum: -6.404733420625232e-05
Epoch: 435 Error Sum: -6.404674483561842e-05
Epoch: 436 Error Sum: -6.40461554754293e-05
Epoch: 437 Erro

Epoch: 849 Error Sum: -6.380366466490848e-05
Epoch: 850 Error Sum: -6.380307972693022e-05
Epoch: 851 Error Sum: -6.380249479958147e-05
Epoch: 852 Error Sum: -6.380190988288306e-05
Epoch: 853 Error Sum: -6.380132497674912e-05
Epoch: 854 Error Sum: -6.38007400810929e-05
Epoch: 855 Error Sum: -6.380015519649382e-05
Epoch: 856 Error Sum: -6.379957032230828e-05
Epoch: 857 Error Sum: -6.379898545866985e-05
Epoch: 858 Error Sum: -6.379840060582401e-05
Epoch: 859 Error Sum: -6.379781576313064e-05
Epoch: 860 Error Sum: -6.379723093172338e-05
Epoch: 861 Error Sum: -6.379664611051456e-05
Epoch: 862 Error Sum: -6.379606129975311e-05
Epoch: 863 Error Sum: -6.379547650023788e-05
Epoch: 864 Error Sum: -6.379489171077102e-05
Epoch: 865 Error Sum: -6.379430693193109e-05
Epoch: 866 Error Sum: -6.379372216396614e-05
Epoch: 867 Error Sum: -6.3793137406341e-05
Epoch: 868 Error Sum: -6.379255265986147e-05
Epoch: 869 Error Sum: -6.379196792343812e-05
Epoch: 870 Error Sum: -6.379138319809532e-05
Epoch: 871 Er

In [40]:
print('Weights:',weights)
print('Bias:',bias)

Weights: [[7.00922425]
 [7.00953281]]
Bias: [-3.14905135]


In [ ]:
# Prediction with the new model for [1,1], groud truth result = 1

In [38]:
single_point = np.array([1,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
result2

array([0.9793702])

In [ ]:
# Prediction with the new model for [0,0], groud truth result = 0

In [39]:
single_point = np.array([0,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
result2

array([0.04112867])